esphome:
  name: pool
  friendly_name: Pool

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "yo+TEyRBqV9PeQWRm1JIE6yOVk9ywrikloOUHNC6mAU="

web_server:

ota:
  - platform: esphome
    password: "efd6cf26347d0a0b45601c73d0ec7d9b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.10.22
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.10.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pool Fallback Hotspot"
    password: "uZ2GKbwgh1Dj"

captive_portal:

one_wire:
  - platform: gpio
    pin: GPIO27



switch:
  #Pool pump control
  - platform: gpio
    pin: GPIO12
    name: Pool Pump

  #Cl pump control
  - platform: gpio
    pin: GPIO14
    name: Cl Pump

  #Ph pump control
  - platform: gpio
    pin: GPIO13
    name: Ph Pump

  #Aux out control
  - platform: gpio
    pin: GPIO15
    name: Aux Output


sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"

#cl sensor
  - platform: adc
    pin: GPIO35
    name: "CL Sensor"
    update_interval: 1s
    filters:
      - multiply: 1000

#ph sensor
  - platform: adc
    pin: GPIO34
    name: "PH Sensor"
    update_interval: 1s
    filters:
      - multiply: 9

#testing 1 wire DS18B20 temp sensor
  - platform: dallas_temp
    name: temperature
    update_interval: 2s

binary_sensor:
  - platform: status
    name: "Connection Status"

#ph low level sensor
  - platform: gpio
    pin: GPIO26
    name: Ph Tank Level

#cl low level sensor
  - platform: gpio
    pin: GPIO25
    name: CL Tank Level


#testing display options
i2c:
  sda: GPIO21
  scl: GPIO22

display:
  - platform: lcd_pcf8574
    dimensions: 20x4
    address: 0x27
    lambda: |-
      it.print("Hello World!");